### ISSUE TITLE
Build system plans

### ISSUE THREAD

**Issue by HW42** [gramineproject/graphene#760] opened 2019-06-18 04:41 UTC
Recently there has been some work on the Makefiles (like PR #732 and PR #759). Before spending too much time on details of the current Makefiles, it would be good to decide how the build system should look like in the mid-term (For example, IIRC, @mkow would like to migrate to cmake at some point).

**Comment by donporter** [comment] 2019-06-18 13:32
I don't personally have strong feelings here.  I'm just trying to get things working as needed, and happy to defer to whoever wants to drive the work.

**Comment by dimakuv** [comment] 2019-06-18 21:58
I concur with Don. I am actually fine with the current Makefile build system (especially with the recent PRs). I am more concerned with Python scripts `pal-sgx-get-token` and `pal-sgx-sign` -- their interface is ugly and they are buried so deep that most people don't recognize how to sign apps out-of-tree. I also dislike our current source tree (`lib/` dir is under Pal, Glibc is under `LibOS/shim`, regression tests are in different subdirs in LibOS and Pal).

**Comment by chiache** [comment] 2019-06-18 23:14
For the long term, I do wish to move on to a more portable building system such as cmake. It might be too much work to do before our stable release deadline. For the time being, we should explore as many options as possible and compare the pros and cons.

**Comment by mkow** [comment] 2019-06-19 00:54
I'd like to migrate to CMake, but rather somewhen in the future (next year maybe?), as we have much bigger issues now. So, for now, let's keep our Makefiles in a good condition, because this seems to be much less work and less possible problems than rewriting everything to CMake.

Also, +1 to the issues @dimakuv pointed out.

**Comment by yamahata** [comment] 2019-06-19 19:45
+1 for cmake.
Given that the migration won't happen soon, so I'm fixing my pain point in short term.

My wish list are
- out-of-source tree build
- build configuration
  "make DEBUG=1 SGX=1" isn't a way for long term.
  For multiple version support of glibc (or musl libc as optional), this would also help.
  People don't want to build all of the version.
- dependency generation
  Yeah, hw42 is resolving this. Great work!
- package script
  packaging script for .deb (or .rpm)
  e.g. "make deb" to generate .deb package.
  I'd like to tell users, "just install package" instead of "follow this install instruction."
- docker image
  we can generate docker image with something like "make docker-image".
  and we can host pre-build docker image so that casual user can download it and play graphene without hassle.

**Comment by mkow** [comment] 2019-06-26 11:48
+1 to Isaku's wishlist, especially I'd like to see out-of-tree builds.
btw. do you have any estimate how hard that migration to CMake would be and what could potentially cause troubles? (other than just generic pain of changing everything and checking whether all things still work)

**Comment by yamahata** [comment] 2019-07-09 19:34
I have no estimation.
In fact I had looked into Makefiles and concluded that Makefiles need to be cleaned up before switching to other build system.
Current Makefiles are really convoluted. they need to be untangled first.

**Comment by yamahata** [comment] 2019-07-29 16:03
one more wish
- sortout host arch and target arch
  Pal/ needs to be compiled for the target arch (Linux, FreeBSD or future platform)
  On the other hand LibOS/ needs to be compiled for Linux. ELF binary.
  Because the current Makefile mixes the two notion, it resulted in ugly ifdefs to prevent building LibOS program.
  Ideally a sort of cross-compile should be enabled. (Maybe this is overkill though.)
  e.g. build Pal/FreeBSD on Linux host, build LibOS on FreeBSD and then run LibOS/shim/test/regression on FreeBSD

**Comment by HW42** [comment] 2019-08-28 22:19
> btw. do you have any estimate how hard that migration to CMake would be and what could potentially cause troubles? (other than just generic pain of changing everything and checking whether all things still work)

No estimate, but one thing which might cause friction is that build systems like CMake try to be high-level and portable. So you basically say "I have a C program here consisting of these files" and CMake will figure out the rest. This might get in the way to when we do non-standard stuff like linker scripts, entry code, etc. OTOH: ReactOS uses CMake so it can't be that bad for low-level stuff.

I never used CMake much. When I needed to interact with it it appeared to me to have a rather high entry bar (While the syntax looks very familiar, actually making changes to achieve your goal needed a lot of reading of documentation).

---

A very different, interesting approach I have seen recently is to have some custom python script which handles the high-level build configuration and then generated [ninja](https://ninja-build.org/) files. This of course has the downside that you don't get things like checking of available features/libraries for free.

**Comment by chiache** [comment] 2019-08-28 22:41
To second @yamahata's suggestion, I believe we should try to untangle the Makefiles first. Right now there is too much cross-directory dependency that makes the building process very hard to track.

As the first step toward something like CMake, I suggest we divide up the building system by components:

- Linux PAL
- SGX PAL
- Other PALs (e.g., FreeBSD PAL)
- GLibc (or Musl)
- LibOS
- Each test or application directory

It would help if we try not to reuse Makefiles and scripts across the components except for just reusing some common functions. We should avoid importing arbitrary Makefiles like `Makefile.Host` or `Makefile.Test` which makes the code overly complex and prone to error. As you might notice, that's exactly what we are trying to do during the process of cleaning up application makefiles.

**Comment by woju** [comment] 2020-10-10 09:04
I propose to switch to meson (https://mesonbuild.com/). It uses ninja to actually invoke the compiler, but apart from invocation this is not visible to the user (it's not needed to write any ninja script).

The transition could be gradual, not everything at the same time, but during the transition period both build systems would have to be invoked one after another, like this:
```sh
make
make SGX=1
meson setup build
ninja -C build
```

As a first step, I made PR #1879, which adds meson configuration only for installation. Next steps would be taken when and if there will be an agreement to proceed.

For an example of `meson.build` file syntax and a comparison to a respective `Makefile`, see this commit, which right now I don't intend to merge: https://github.com/oscarlab/graphene/commit/b7dc2f6268def59cc6343361231ba69e6c2bfb04.

Meson supports out-of-tree builds (and only those), has built-in mechanism of options for build configuration, and automatically tracks dependencies, so first three points of @yamahata's [wishlist](#issuecomment-503719851) will be easy.

Meson is available either as distro package or python package from pip. On debian 10 it is a reasonably new package, but on ubuntu 18.04 the package is old, but it can be installed from pip instead.

I'd hope the transition would also be an opportunity to have some general source tree cleanup, as suggested by @dimakuv in [previous comment](#issuecomment-503327805).

**Comment by mkow** [comment] 2020-10-11 17:51
Sounds good. From my side: I'd vote for either Meson or Bazel. Bazel's big disadvantages are that it isn't available in repos and it's written in Java, but I like their `--sandbox` option to debug incorrect dependencies, which is AFAIK lacking in meson. Bazel is also more widely used, so I guess support for many things may be better. I'm not sure about other differences.

**Comment by dimakuv** [comment] 2020-10-12 09:04
First time I hear about `meson` but looks good. I'm fine with it.

**Comment by yamahata** [comment] 2020-10-12 18:19
I'm fine with meson. Actually I don't have strong opinion about meson vs cmake (or other popular ones.)

**Comment by dimakuv** [comment] 2021-09-23 11:17
Since the transition to Meson is (almost) complete, I'm closing this issue. I didn't find any particular things that could be useful in the new Gramine repo.

**Closed by dimakuv** 2021-09-23 11:17 UTC
Labels: feature request, P: 0
