### ISSUE TITLE
sendfile syscall fails to copies data when offset argument is specified

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/graphene#2541] opened 2021-07-14 06:26 UTC
## Description of the problem
sendfile returns -1 when sendfile syscall is tested with different offset argument specified

Testcase to test the basic functionality of the sendfile(2) system call.
call sendfile(2) with offset = 0
call sendfile(2) with offset in the middle of the file(2, 4, 6)

If offset is not NULL, then it points to a variable holding the file offset from which sendfile() will start reading data from in_fd.  When sendfile() returns, this variable will be set to the offset of the byte following the last byte that was read.  If offset is not NULL, then sendfile() does not modify the file offset of in_fd; otherwise the file offset is adjusted to reflect the number of bytes read from in_fd.
If the transfer was successful, the number of bytes written to out_fd is returned

## Steps to reproduce
Run LTP test sendfile02

## Expected results
sendfile02    1  TPASS  :  functionality of sendfile() is correct
sendfile02    2  TPASS  :  functionality of sendfile() is correct
sendfile02    3  TPASS  :  functionality of sendfile() is correct
sendfile02    4  TPASS  :  functionality of sendfile() is correct

## Actual results
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
sendfile02    1  TFAIL  :  sendfile(2) failed to return expected value, expected: 26, got: -1
sendfile02    2  TFAIL  :  sendfile(2) failed to return expected value, expected: 24, got: -1
sendfile02    3  TFAIL  :  sendfile(2) failed to return expected value, expected: 22, got: -1
sendfile02    4  TFAIL  :  sendfile(2) failed to return expected value, expected: 20, got: -1
[P2292:T5:sendfile02] error: Failed to send IPC msg to 2284: -32
[P2292:T5:sendfile02] error: Sending IPC process-exit notification failed: -13

## Label
P0, bug

**Comment by dimakuv** [comment] 2021-07-15 11:06
This is dependent on https://github.com/gramineproject/gramine/issues/21 and #2531. Looks like the same issue.

**Comment by dimakuv** [comment] 2021-08-11 07:06
Tracked in meta-issue https://github.com/gramineproject/gramine/issues/21, closing here.

**Comment by boryspoplawski** [comment] 2021-09-09 15:27
This is completely unrelated to https://github.com/gramineproject/gramine/issues/21 (it prints an error message, but it's expected and long after test already failed).

**Comment by jkr0103** [comment] 2021-10-06 03:14
Please assign to me

**Comment by jkr0103** [comment] 2021-10-07 04:13
I am unable to reproduce the issue with below commits until Jul on Ubuntu 18.04 and Kernel 5.11.0-rc7-intel-next+. Please share the commit ID, OS and kernel version of machine where issue was seen.

commit f7e2a7793e2031d5feec0f1faf5f30ba9320bf5e (HEAD)
Date:   Thu Sep 9 03:01:03 2021 -0700

commit e637fab1af3e0a348d6ded339f3a84bdbe747ed9
Date:   Thu Sep 23 03:37:24 2021 +0200

commit 6a7fdaf981649f409df4c30fa6489478307224c9
Date:   Wed Jul 7 03:01:58 2021 +0200

**Comment by jinengandhi-intel** [comment] 2021-10-13 04:12
This issue is not reproducible with the latest Gramine master, might have been unknowingly fixed by some commit in the past few weeks. @dimakuv can you close this issue? Anjali is out and I don't have permissions to close issues.

**Comment by dimakuv** [comment] 2021-10-13 06:26
@jinengandhi-intel Thanks for verifying!

**Closed** 2021-10-13 06:26 UTC
Labels: bug, P: 1
