### ISSUE TITLE
lstat syscall fails to provide the right st.mode, uid gid etc. when the path is a symbolic link

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/graphene#2069] opened 2021-01-08 11:04 UTC
## Description of the problem

When a symbolic link path is provided to lstat, Linux native rightly reports the st.mode as symbolic link whereas when run with Graphene native it st.mode is reported as a regular file.

```
Native Run:

./lstat01
graphene/LibOS/shim/test/ltp/src/lib/tst_test.c:1248: TINFO: Timeout per run is 0h 05m 00s
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:39: TINFO: stat_buf.st_mode 120000
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:40: TINFO: stat_buf.st_uid 1000
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:41: TINFO: stat_buf.st_gid 1000
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:42: TINFO: stat_buf.st_size 13
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:51: TPASS: lstat() reported correct values for the symlink!

Graphene Run:

./pal_loader ./lstat01
WARNING: Using insecure argv source. Don't use this configuration in production!
graphene/LibOS/shim/test/ltp/src/lib/tst_test.c:1248: TINFO: Timeout per run is 0h 05m 00s
WARNING: Using insecure argv source. Don't use this configuration in production!
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:39: TINFO: stat_buf.st_mode 100000
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:40: TINFO: stat_buf.st_uid 0
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:41: TINFO: stat_buf.st_gid 0
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:42: TINFO: stat_buf.st_size 0
graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/lstat/lstat01.c:48: TFAIL: lstat() reported incorrect values for the symlink!

```

## Steps to reproduce

The issue was debugged by analyzing the lstat test from LTP test suite. lstat01 test was failing in the setup with some ENOSYS, so we split the test to run the setup separately in Linux native and only the lstat syscall is run in Graphene.

I have attached the zip which has the source files as well as the pre-built binaries. You can just place the binaries inside LibOS/shim/test/ltp/install/testcases/bin. First run the lstat_setup in native and then run lstat01 with Graphene. 

[lstat_issue.zip](https://github.com/oscarlab/graphene/files/5786773/lstat_issue.zip)

**Comment by mkow** [comment] 2021-01-08 14:17
This is a known issue, see #1803.

**Comment by anjalirx-intel** [comment] 2021-07-13 06:45
Retested with release 1.2rc1 and issue is still reproducible

**Comment by pwmarcz** [comment] 2021-09-09 11:22
Right now this is by design: Graphene does not expose host-level symlinks as symlinks.

We haven't decided yet how to solve this: we can either expose host-level symlinks, or support applications creating a symlink in Graphene by creating an in-memory entry (same as we do for named pipes and Unix sockets).

**Comment by mkow** [comment] 2021-09-09 17:49
@jinengandhi-intel: Do I understand correctly, that this test checks host-level symlinks? If so, that's currently not implemented as Paweł said and these tests fail as expected. So, we can close this issue if that's the case.

**Closed** 2021-09-16 08:25 UTC
Labels: bug, P: 1
