### ISSUE TITLE
chroot_rename corrupts handles open to old file

### ISSUE THREAD

**Issue by smherwig** [gramineproject/graphene#382] opened 2018-12-11 19:54 UTC
If an application holds a handle for an open file `foo`, and `foo` is renamed to `bar`, then the handle's data is modified by `chroot_rename`.  In particular, the statement `atomic_set(&old_data->size, 0)` in `chroot/fs.c`'s implemenation of `chroot_rename` means that that the handle is now to a zero-sized file.

The effects of this bug are particularly pernicious if the handle is used as the input handle argument to `sendfile`.  In particular, in `sys/shim_fs.c`, `shim_do_sendfile` calls `handle_copy`.   In `handle_copy`, chroot fs's `poll` callback is called to get the size of the file (which has been erroneously set to 0), causing the `count` variable to be set to `size - offi` -- a negative number.

**Comment by donporter** [comment] 2019-01-02 20:04
Thanks for the bug report!  Do you happen to have a simple test case that can reproduce the problem easily?

**Comment by boryspoplawski** [comment] 2019-08-21 22:22
Could you check if the problem still persists on #943 or give us a test case that triggers the bug you described?

**Comment by dimakuv** [comment] 2021-07-14 09:35
From what I see, the issue is still there: https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/LibOS/shim/src/fs/chroot/fs.c#L1013

Definitely looks like a bug. Assigning Priority 1 to this. Hopefully will be fixed as part of a Big Chroot Rewrite.

**Closed** 2021-09-12 14:03 UTC
Labels: bug, P: 1
