### ISSUE TITLE
Graphene-SGX: Syscalls wakes up early/prematurely on Server Machines

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/graphene#2666] opened 2021-08-27 07:06 UTC
## Description of the problem
When Kernel Timer Precision Tests are run on Server machines, the tests are failing with woken up early error.

These below mentioned syscalls wakes up early on servers

clock_nanosleep02
epoll_wait02
nanosleep01
poll02
pselect01
pselect01_64
select04
futex_wait05

## Steps to reproduce
Run LTP tests with SGX=1

## Actual results
**graphene-sgx clock_nanosleep02:**
```
TINFO: Timeout per run is 0h 05m 00s
sh: 1: systemd-detect-virt: Permission denied
TINFO: CLOCK_MONOTONIC resolution 1000ns
TINFO: prctl(PR_GET_TIMERSLACK) = -1, using 50us
TINFO: Failed to set zero latency constraint: No such file or directory
TINFO: clock_nanosleep() sleeping for 1000us 500 iterations, threshold 452.01us
TINFO: min 1072us, max 1179us, median 1117us, trunc mean 1123.27us (discarded 25)
TPASS: Measured times are within thresholds
TINFO: clock_nanosleep() sleeping for 2000us 500 iterations, threshold 452.01us
TINFO: min 2074us, max 2179us, median 2120us, trunc mean 2123.49us (discarded 25)
TPASS: Measured times are within thresholds
TINFO: clock_nanosleep() sleeping for 5000us 300 iterations, threshold 452.04us
TINFO: min 5107us, max 5168us, median 5118us, trunc mean 5122.92us (discarded 15)
TPASS: Measured times are within thresholds
TINFO: clock_nanosleep() sleeping for 10000us 100 iterations, threshold 452.33us
TINFO: min 10098us, max 10155us, median 10106us, trunc mean 10112.55us (discarded 5)
TPASS: Measured times are within thresholds
TINFO: clock_nanosleep() sleeping for 25000us 50 iterations, threshold 453.29us
TINFO: min 25063us, max 25118us, median 25073us, trunc mean 25079.50us (discarded 2)
TPASS: Measured times are within thresholds
TINFO: clock_nanosleep() sleeping for 100000us 10 iterations, threshold 539.00us

> TFAIL: clock_nanosleep() woken up early 10 times range: [99930,99888]

TINFO: min 99888us, max 99930us, median 99896us, trunc mean 99895.44us (discarded 1)
TINFO: clock_nanosleep() sleeping for 1000000us 2 iterations, threshold 4402.00us

> TFAIL: clock_nanosleep() woken up early 1 times range: [997777,997777]

TINFO: min 997777us, max 1022596us, median 997777us, trunc mean 997777.00us (discarded 1)

Summary:
passed   0
failed   0
skipped  0
warnings 0
```

**Comment by mkow** [comment] 2021-08-31 10:56
@anjalirai-intel: Are you planning to submit a PR with this? If not, I can do this.

**Comment by anjalirai-intel** [comment] 2021-08-31 10:58
@mkow We are waiting for reply from Anees, And then I can submit the PR

**Comment by aneessahib** [comment] 2021-09-01 03:37
@mkow this ones a slightly different issue (atleast looks a bit different). may not be related to C-states, but if it is then we can close this one too. will get back soon.

**Comment by aneessahib** [comment] 2021-09-07 15:48
On some systems - the RDTSC and the system clock drifts away from each other significantly, that at higher gaps (above 100ms), rdtsc falls behind, and this gets flagged by LTP. Currently the correction is done every 10seconds  ```#define TSC_REFINE_INIT_TIMEOUT_USECS 10000000 ``` . Reducing this timeout further could resolve this issue, but might have a perf impact. 
@dimakuv - i think 10s timeout is too late for a correction. One second should be reasonable without any perf impact (although it may not help pass the test since it fails as early as 100ms itself. I remember switching to rdtsc  had improved specpower benchmarks significantly - i can get this retested with 100ms and 1s timeout to see if readjusting the timeout is feasible solution?

**Comment by dimakuv** [comment] 2021-09-07 16:41
@aneessahib Reducing our hard-coded timeout from 10 seconds to e.g. 1 second makes sense. Please try it out on a couple workloads, and if their performance doesn't change much, then no problem.

The original 10 second timeout value was chosen without any good justification, other than it is definitely good enough. We can decrease this constant as we see suitable.

Decreasing to 100 milliseconds sounds risky though. 100 ms sounds it can have a non-negligible impact on performance of typical workloads. But worth an experiment.

**Comment by jinengandhi-intel** [comment] 2021-09-23 10:17
@mkow @dimakuv @aneessahib Can you re-open the issue? Seems like the issue is not completely fixed and we still see tests failing with woken up early message on a server but its is very intermittent. Please find attached logs for 2 of the tests where I was able to repro the issue 1 in 8/9 times. (Search for TFAIL in the logs)

In terms of priority it can definitely go down as the issue is not consistent like before.

[select04_woken_up_early.txt](https://github.com/gramineproject/graphene/files/7216732/select04_woken_up_early.txt)
[epoll_wait02_woken_up_early.txt](https://github.com/gramineproject/graphene/files/7216733/epoll_wait02_woken_up_early.txt)

**Comment by aneessahib** [comment] 2021-09-24 04:21
so what we are seeing here is expected. looks like on this system, the negative time drift is detected as early as 25ms, which is why the test fails only at that point, and begins to pass soon as it goes above 50ms. Unfortunately, we cant correct this anymore as there could be a perf impact. 

The original issue that was fixed was for a 100% reproducible time drift issue. And now since this residual problem is quite infrequent (1 out 8) times, i think we can leave it as is for now, or may be close with a documentation.

**Comment by dimakuv** [comment] 2021-09-24 09:12
I generally agree with @aneessahib. ~~Since this is not a real "bug" (it is simply that timestamp reported by Gramine may be very slightly off in comparison to the previous timestamp), and it only exhibits itself in an LTP test (and not on any real workload), we could ignore it for now. (**this comment was wrong, so I mark it as cut out**)~~

**Comment by mkow** [comment] 2021-09-24 23:17
Hmm, but it's pretty bad that we can expose negative time delta to the application. The LTP test exposes it consistently, but normal apps may still hit it sporadically, just not as often as this specialized test.

**Comment by dimakuv** [comment] 2021-09-27 07:42
@mkow Sorry, I think I got confused by the two issues. My comment about the "negative time delta" concerned this issue: https://github.com/gramineproject/gramine/issues/82.

The issue here is different: here the complaint is that the time drift is observable after a tiny amount of time (25ms), and we only recalibrate the time drift with 50ms periodicity (see https://github.com/gramineproject/gramine/pull/38/files). Setting the recalibration period to less than 50ms would hurt normal workloads (e.g., Redis), so we don't want to decrease this period further.

**Comment by mkow** [comment] 2021-09-28 11:30
Ah, I see. Then it's not very important. This test is disabled anyways in the public CI because it requires disabling C-states, so I think we can just close this issue as we don't plan to do anything more about it.

**Closed by mkow** 2021-09-28 11:30 UTC
Labels: bug, P: 2
